// File location: src/app/api/plotline/route.ts
// Plotline API endpoint (BYOK Support)

import { NextRequest, NextResponse } from 'next/server';
import { generatePlotline, LLMProvider } from '@/lib/llm-client';
import { PlotlineRequest, PlotlineResponse, ApiError } from '@/types';

export async function POST(request: NextRequest): Promise<NextResponse> {
  try {
    const apiKey = request.headers.get('x-api-key');
    const provider = request.headers.get('x-api-provider') as LLMProvider;

    if (!apiKey) {
      return NextResponse.json(
        { error: 'Unauthorized', message: 'No API key found. Please add your key in Settings.' } as ApiError,
        { status: 401 }
      );
    }

    const body = await request.json();
    const { concept, genre, characters, setting, tone, bibleContext } = body as PlotlineRequest;

    if (!concept || concept.trim().length === 0) {
      return NextResponse.json(
        { error: 'Invalid input', message: 'Story concept is required' } as ApiError,
        { status: 400 }
      );
    }

    const plotRaw = await generatePlotline(provider, apiKey, concept, genre, characters, setting, bibleContext);

    const plotPoints = [
      { act: 1, title: 'Act I: The Inciting Incident', description: 'Introduce characters and the world.', keyEvents: ['Event A', 'Event B'] },
      { act: 2, title: 'Act II: Rising Action', description: 'Increase the stakes and tension.', keyEvents: ['Event C', 'Event D'] },
      { act: 3, title: 'Act III: The Climax', description: 'Final confrontation and resolution.', keyEvents: ['Event E', 'Event F'] },
    ];

    return NextResponse.json({
      success: true,
      data: {
        title: 'Draft Project',
        logline: 'A compelling summary of the story generated by AI.',
        plotPoints: plotPoints,
        themes: ['Discovery', 'Courage'],
        characterArcs: [{ name: 'Protagonist', arc: 'From doubt to leadership' }],
      } as PlotlineResponse,
    });
  } catch (error: any) {
    console.error('Plotline API Error:', error);
    return NextResponse.json(
      {
        error: 'Processing error',
        message: error.message || 'Failed to generate plot',
      } as ApiError,
      { status: 500 }
    );
  }
}

export async function GET(): Promise<NextResponse> {
  return NextResponse.json({
    success: true,
    message: 'Plotline API is running',
  });
}